"""Reference index constituent tickers (display-only snapshot).

Snapshot taken 2026-06-09 from Wikipedia (current constituents at fetch
time; lists drift with index rebalances — refresh before relying on them):

- S&P 500: https://en.wikipedia.org/wiki/List_of_S%26P_500_companies
- Nasdaq-100: https://en.wikipedia.org/wiki/Nasdaq-100
- Russell 1000: https://en.wikipedia.org/wiki/Russell_1000_Index

These universes are DISPLAY-ONLY context for the dashboard identifier
panel.  The country-rotation platform trades country indices, not
single stocks; nothing here feeds the engine, scores or validation.
"""
from __future__ import annotations

AS_OF = "2026-06-09"

SOURCE_URLS = {
    "S&P 500": "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies",
    "Nasdaq-100": "https://en.wikipedia.org/wiki/Nasdaq-100",
    "Russell 1000": "https://en.wikipedia.org/wiki/Russell_1000_Index",
}

CONSTITUENTS: dict[str, list[str]] = {
    "S&P 500": [
        "A", "AAPL", "ABBV", "ABNB", "ABT", "ACGL", "ACN", "ADBE", "ADI", "ADM",
        "ADP", "ADSK", "AEE", "AEP", "AES", "AFL", "AIG", "AIZ", "AJG", "AKAM",
        "ALB", "ALGN", "ALL", "ALLE", "AMAT", "AMCR", "AMD", "AME", "AMGN", "AMP",
        "AMT", "AMZN", "ANET", "AON", "AOS", "APA", "APD", "APH", "APO", "APP",
        "APTV", "ARE", "ARES", "ATO", "AVB", "AVGO", "AVY", "AWK", "AXON", "AXP",
        "AZO", "BA", "BAC", "BALL", "BAX", "BBY", "BDX", "BEN", "BF.B", "BG",
        "BIIB", "BKNG", "BKR", "BLDR", "BLK", "BMY", "BNY", "BR", "BRK.B", "BRO",
        "BSX", "BX", "BXP", "C", "CAG", "CAH", "CARR", "CASY", "CAT", "CB",
        "CBOE", "CBRE", "CCI", "CCL", "CDNS", "CDW", "CEG", "CF", "CFG", "CHD",
        "CHRW", "CHTR", "CI", "CIEN", "CINF", "CL", "CLX", "CMCSA", "CME", "CMG",
        "CMI", "CMS", "CNC", "CNP", "COF", "COHR", "COIN", "COO", "COP", "COR",
        "COST", "CPAY", "CPB", "CPRT", "CPT", "CRH", "CRL", "CRM", "CRWD", "CSCO",
        "CSGP", "CSX", "CTAS", "CTSH", "CTVA", "CVNA", "CVS", "CVX", "D", "DAL",
        "DASH", "DD", "DDOG", "DE", "DECK", "DELL", "DG", "DGX", "DHI", "DHR",
        "DIS", "DLR", "DLTR", "DOC", "DOV", "DOW", "DPZ", "DRI", "DTE", "DUK",
        "DVA", "DVN", "DXCM", "EA", "EBAY", "ECL", "ED", "EFX", "EG", "EIX",
        "EL", "ELV", "EME", "EMR", "EOG", "EQIX", "EQR", "EQT", "ERIE", "ES",
        "ESS", "ETN", "ETR", "EVRG", "EW", "EXC", "EXE", "EXPD", "EXPE", "EXR",
        "F", "FANG", "FAST", "FCX", "FDS", "FDX", "FDXF", "FE", "FFIV", "FICO",
        "FIS", "FISV", "FITB", "FIX", "FOX", "FOXA", "FRT", "FSLR", "FTNT", "FTV",
        "GD", "GDDY", "GE", "GEHC", "GEN", "GEV", "GILD", "GIS", "GL", "GLW",
        "GM", "GNRC", "GOOG", "GOOGL", "GPC", "GPN", "GRMN", "GS", "GWW", "HAL",
        "HAS", "HBAN", "HCA", "HD", "HIG", "HII", "HLT", "HON", "HOOD", "HPE",
        "HPQ", "HRL", "HSIC", "HST", "HSY", "HUBB", "HUM", "HWM", "IBKR", "IBM",
        "ICE", "IDXX", "IEX", "IFF", "INCY", "INTC", "INTU", "INVH", "IP", "IQV",
        "IR", "IRM", "ISRG", "IT", "ITW", "IVZ", "J", "JBHT", "JBL", "JCI",
        "JKHY", "JNJ", "JPM", "KDP", "KEY", "KEYS", "KHC", "KIM", "KKR", "KLAC",
        "KMB", "KMI", "KO", "KR", "KVUE", "L", "LDOS", "LEN", "LH", "LHX",
        "LII", "LIN", "LITE", "LLY", "LMT", "LNT", "LOW", "LRCX", "LULU", "LUV",
        "LVS", "LYB", "LYV", "MA", "MAA", "MAR", "MAS", "MCD", "MCHP", "MCK",
        "MCO", "MDLZ", "MDT", "MET", "META", "MGM", "MKC", "MLM", "MMM", "MNST",
        "MO", "MOS", "MPC", "MPWR", "MRK", "MRNA", "MRSH", "MS", "MSCI", "MSFT",
        "MSI", "MTB", "MTD", "MU", "NCLH", "NDAQ", "NDSN", "NEE", "NEM", "NFLX",
        "NI", "NKE", "NOC", "NOW", "NRG", "NSC", "NTAP", "NTRS", "NUE", "NVDA",
        "NVR", "NWS", "NWSA", "NXPI", "O", "ODFL", "OKE", "OMC", "ON", "ORCL",
        "ORLY", "OTIS", "OXY", "PANW", "PAYX", "PCAR", "PCG", "PEG", "PEP", "PFE",
        "PFG", "PG", "PGR", "PH", "PHM", "PKG", "PLD", "PLTR", "PM", "PNC",
        "PNR", "PNW", "PODD", "POOL", "PPG", "PPL", "PRU", "PSA", "PSKY", "PSX",
        "PTC", "PWR", "PYPL", "Q", "QCOM", "RCL", "REG", "REGN", "RF", "RJF",
        "RL", "RMD", "ROK", "ROL", "ROP", "ROST", "RSG", "RTX", "RVTY", "SATS",
        "SBAC", "SBUX", "SCHW", "SHW", "SJM", "SLB", "SMCI", "SNA", "SNDK", "SNPS",
        "SO", "SOLV", "SPG", "SPGI", "SRE", "STE", "STLD", "STT", "STX", "STZ",
        "SW", "SWK", "SWKS", "SYF", "SYK", "SYY", "T", "TAP", "TDG", "TDY",
        "TECH", "TEL", "TER", "TFC", "TGT", "TJX", "TKO", "TMO", "TMUS", "TPL",
        "TPR", "TRGP", "TRMB", "TROW", "TRV", "TSCO", "TSLA", "TSN", "TT", "TTD",
        "TTWO", "TXN", "TXT", "TYL", "UAL", "UBER", "UDR", "UHS", "ULTA", "UNH",
        "UNP", "UPS", "URI", "USB", "V", "VEEV", "VICI", "VLO", "VLTO", "VMC",
        "VRSK", "VRSN", "VRT", "VRTX", "VST", "VTR", "VTRS", "VZ", "WAB", "WAT",
        "WBD", "WDAY", "WDC", "WEC", "WELL", "WFC", "WM", "WMB", "WMT", "WRB",
        "WSM", "WST", "WTW", "WY", "WYNN", "XEL", "XOM", "XYL", "XYZ", "YUM",
        "ZBH", "ZBRA", "ZTS",
    ],
    "Nasdaq-100": [
        "AAPL", "ABNB", "ADBE", "ADI", "ADP", "ADSK", "AEP", "ALNY", "AMAT", "AMD",
        "AMGN", "AMZN", "APP", "ARM", "ASML", "AVGO", "AXON", "BKNG", "BKR", "CCEP",
        "CDNS", "CEG", "CHTR", "CMCSA", "COST", "CPRT", "CRWD", "CSCO", "CSX", "CTAS",
        "CTSH", "DASH", "DDOG", "DXCM", "EA", "EXC", "FANG", "FAST", "FER", "FTNT",
        "GEHC", "GILD", "GOOG", "GOOGL", "HON", "IDXX", "INSM", "INTC", "INTU", "ISRG",
        "KDP", "KHC", "KLAC", "LIN", "LITE", "LRCX", "MAR", "MCHP", "MDLZ", "MELI",
        "META", "MNST", "MPWR", "MRVL", "MSFT", "MSTR", "MU", "NFLX", "NVDA", "NXPI",
        "ODFL", "ORLY", "PANW", "PAYX", "PCAR", "PDD", "PEP", "PLTR", "PYPL", "QCOM",
        "REGN", "ROP", "ROST", "SBUX", "SHOP", "SNDK", "SNPS", "STX", "TMUS", "TRI",
        "TSLA", "TTWO", "TXN", "VRSK", "VRTX", "WBD", "WDAY", "WDC", "WMT", "XEL",
        "ZS",
    ],
    "Russell 1000": [
        "A", "AA", "AAL", "AAON", "AAPL", "ABBV", "ABNB", "ABT", "ACGL", "ACHC",
        "ACI", "ACM", "ACN", "ADBE", "ADC", "ADI", "ADM", "ADP", "ADSK", "ADT",
        "AEE", "AEP", "AES", "AFG", "AFL", "AFRM", "AGCO", "AGNC", "AGO", "AIG",
        "AIT", "AIZ", "AJG", "AKAM", "AL", "ALAB", "ALB", "ALGM", "ALGN", "ALK",
        "ALL", "ALLE", "ALLY", "ALNY", "ALSN", "AM", "AMAT", "AMCR", "AMD", "AME",
        "AMG", "AMGN", "AMH", "AMKR", "AMP", "AMT", "AMTM", "AMZN", "AN", "ANET",
        "AON", "AOS", "APA", "APD", "APG", "APH", "APO", "APP", "APPF", "APTV",
        "AR", "ARE", "ARES", "ARMK", "ARW", "AS", "ASH", "ASTS", "ATI", "ATO",
        "ATR", "AU", "AUR", "AVB", "AVGO", "AVT", "AVTR", "AVY", "AWI", "AWK",
        "AXON", "AXP", "AXS", "AXTA", "AYI", "AZO", "BA", "BAC", "BAH", "BALL",
        "BAM", "BAX", "BBWI", "BBY", "BC", "BDX", "BEN", "BEPC", "BF.A", "BF.B",
        "BFAM", "BG", "BHF", "BIIB", "BILL", "BIO", "BIRK", "BJ", "BKNG", "BKR",
        "BLD", "BLDR", "BLK", "BLSH", "BMRN", "BMY", "BNY", "BOKF", "BPOP", "BR",
        "BRBR", "BRK.B", "BRKR", "BRO", "BROS", "BRX", "BSX", "BSY", "BURL", "BWA",
        "BWXT", "BX", "BXP", "BYD", "C", "CACC", "CACI", "CAG", "CAH", "CAI",
        "CAR", "CARR", "CART", "CASY", "CAT", "CAVA", "CB", "CBC", "CBOE", "CBRE",
        "CBSH", "CCC", "CCI", "CCK", "CCL", "CDNS", "CDW", "CE", "CEG", "CELH",
        "CERT", "CF", "CFG", "CFR", "CG", "CGNX", "CHD", "CHDN", "CHE", "CHH",
        "CHRD", "CHRW", "CHTR", "CHWY", "CI", "CIEN", "CINF", "CL", "CLF", "CLH",
        "CLVT", "CLX", "CMCSA", "CME", "CMG", "CMI", "CMS", "CNA", "CNC", "CNH",
        "CNM", "CNP", "CNXC", "COF", "COHR", "COIN", "COKE", "COLB", "COLD", "COLM",
        "COO", "COP", "COR", "CORT", "COST", "COTY", "CPAY", "CPB", "CPNG", "CPRT",
        "CPT", "CR", "CRCL", "CRH", "CRL", "CRM", "CROX", "CRS", "CRUS", "CRWD",
        "CSCO", "CSGP", "CSL", "CSX", "CTAS", "CTSH", "CTVA", "CUBE", "CUZ", "CVNA",
        "CVS", "CVX", "CW", "CWEN", "CWEN.A", "CXT", "CZR", "D", "DAL", "DAR",
        "DASH", "DBX", "DCI", "DD", "DDOG", "DDS", "DE", "DECK", "DELL", "DG",
        "DGX", "DHI", "DHR", "DINO", "DIS", "DJT", "DKNG", "DKS", "DLB", "DLR",
        "DLTR", "DOC", "DOCS", "DOCU", "DOV", "DOW", "DOX", "DPZ", "DRI", "DRS",
        "DT", "DTE", "DTM", "DUK", "DUOL", "DV", "DVA", "DVN", "DXC", "DXCM",
        "EA", "EBAY", "ECG", "ECL", "ED", "EEFT", "EFX", "EG", "EGP", "EHC",
        "EIX", "EL", "ELAN", "ELF", "ELS", "ELV", "EME", "EMN", "EMR", "ENPH",
        "ENTG", "EOG", "EPAM", "EPR", "EQH", "EQIX", "EQR", "EQT", "ES", "ESAB",
        "ESI", "ESS", "ESTC", "ETN", "ETR", "ETSY", "EVR", "EVRG", "EW", "EWBC",
        "EXC", "EXE", "EXEL", "EXLS", "EXP", "EXPD", "EXPE", "EXR", "F", "FAF",
        "FANG", "FAST", "FBIN", "FCN", "FCNCA", "FCX", "FDS", "FDX", "FDXF", "FE",
        "FERG", "FFIV", "FHB", "FHN", "FICO", "FIGR", "FIS", "FISV", "FITB", "FIVE",
        "FIX", "FLEX", "FLO", "FLS", "FLUT", "FMC", "FNB", "FND", "FNF", "FOUR",
        "FOX", "FOXA", "FR", "FRHC", "FRMI", "FRPT", "FRT", "FSLR", "FTAI", "FTI",
        "FTNT", "FTV", "FWONA", "FWONK", "G", "GAP", "GD", "GDDY", "GE", "GEHC",
        "GEN", "GEV", "GFS", "GGG", "GILD", "GIS", "GL", "GLIBA", "GLIBK", "GLOB",
        "GLPI", "GLW", "GM", "GME", "GMED", "GNRC", "GNTX", "GOOG", "GOOGL", "GPC",
        "GPK", "GPN", "GRMN", "GS", "GTES", "GTLB", "GTM", "GWRE", "GWW", "GXO",
        "H", "HAL", "HALO", "HAS", "HAYW", "HBAN", "HCA", "HD", "HEI", "HEI.A",
        "HHH", "HIG", "HII", "HIW", "HLI", "HLNE", "HLT", "HOG", "HON", "HOOD",
        "HPE", "HPQ", "HR", "HRB", "HRL", "HSIC", "HST", "HSY", "HUBB", "HUBS",
        "HUM", "HUN", "HWM", "HXL", "IBKR", "IBM", "ICE", "IDA", "IDXX", "IEX",
        "IFF", "ILMN", "INCY", "INGM", "INGR", "INSM", "INSP", "INTC", "INTU", "INVH",
        "IONS", "IOT", "IP", "IPGP", "IQV", "IR", "IRDM", "IRM", "ISRG", "IT",
        "ITT", "ITW", "IVZ", "J", "JAZZ", "JBHT", "JBL", "JCI", "JEF", "JHG",
        "JHX", "JKHY", "JLL", "JNJ", "JPM", "KBR", "KD", "KDP", "KEX", "KEY",
        "KEYS", "KHC", "KIM", "KKR", "KLAC", "KMB", "KMI", "KMPR", "KMX", "KNSL",
        "KNX", "KO", "KR", "KRC", "KRMN", "KVUE", "L", "LAD", "LAMR", "LAZ",
        "LBRDA", "LBRDK", "LBTYA", "LBTYK", "LCID", "LDOS", "LEA", "LECO", "LEN", "LEN.B",
        "LFUS", "LH", "LHX", "LII", "LIN", "LINE", "LITE", "LKQ", "LLY", "LLYVA",
        "LLYVK", "LMT", "LNC", "LNG", "LNT", "LOAR", "LOPE", "LOW", "LPLA", "LPX",
        "LRCX", "LSCC", "LSTR", "LULU", "LUV", "LVS", "LW", "LYB", "LYFT", "LYV",
        "M", "MA", "MAA", "MAN", "MANH", "MAR", "MAS", "MASI", "MAT", "MCD",
        "MCHP", "MCK", "MCO", "MDB", "MDLN", "MDLZ", "MDT", "MDU", "MEDP", "MET",
        "META", "MGM", "MHK", "MIDD", "MKC", "MKL", "MKSI", "MKTX", "MLI", "MLM",
        "MMM", "MNST", "MO", "MOH", "MORN", "MOS", "MP", "MPC", "MPT", "MPWR",
        "MRK", "MRNA", "MRP", "MRSH", "MRVL", "MS", "MSA", "MSCI", "MSFT", "MSGS",
        "MSI", "MSM", "MSTR", "MTB", "MTCH", "MTD", "MTDR", "MTG", "MTN", "MTSI",
        "MTZ", "MU", "MUSA", "NBIX", "NCLH", "NCNO", "NDAQ", "NDSN", "NEE", "NEM",
        "NET", "NEU", "NFG", "NFLX", "NI", "NIQ", "NKE", "NLY", "NNN", "NOC",
        "NOV", "NOW", "NRG", "NSA", "NSC", "NTAP", "NTNX", "NTRA", "NTRS", "NU",
        "NUE", "NVDA", "NVR", "NVST", "NVT", "NWL", "NWS", "NWSA", "NXST", "NYT",
        "O", "OC", "ODFL", "OGE", "OGN", "OHI", "OKE", "OKTA", "OLED", "OLLI",
        "OLN", "OMC", "OMF", "ON", "ONON", "ONTO", "ORCL", "ORI", "ORLY", "OSK",
        "OTIS", "OVV", "OWL", "OXY", "OZK", "P", "PAG", "PANW", "PATH", "PAYC",
        "PAYX", "PB", "PCAR", "PCG", "PCOR", "PCTY", "PEG", "PEGA", "PEN", "PENN",
        "PEP", "PFE", "PFG", "PFGC", "PG", "PGR", "PH", "PHM", "PINS", "PK",
        "PKG", "PLD", "PLNT", "PLTR", "PM", "PNC", "PNFP", "PNR", "PNW", "PODD",
        "POOL", "POST", "PPC", "PPG", "PPL", "PPLI", "PR", "PRGO", "PRI", "PRMB",
        "PRU", "PSA", "PSN", "PSX", "PTC", "PVH", "PWR", "PYPL", "Q", "QCOM",
        "QGEN", "QRVO", "QS", "QSR", "QXO", "R", "RAL", "RARE", "RBA", "RBC",
        "RBLX", "RBRK", "RCL", "RDDT", "REG", "REGN", "REXR", "REYN", "RF", "RGA",
        "RGEN", "RGLD", "RH", "RHI", "RITM", "RIVN", "RJF", "RKLB", "RKT", "RL",
        "RLI", "RMD", "RNG", "RNR", "ROIV", "ROK", "ROKU", "ROL", "ROP", "ROST",
        "RPM", "RPRX", "RRC", "RRX", "RS", "RSG", "RTX", "RVMD", "RVTY", "RYAN",
        "RYN", "S", "SAIA", "SAIC", "SAIL", "SAM", "SARO", "SBAC", "SBUX", "SCCO",
        "SCHW", "SCI", "SEB", "SEIC", "SF", "SFD", "SFM", "SGI", "SHC", "SHW",
        "SIRI", "SITE", "SJM", "SLB", "SLGN", "SLM", "SMCI", "SMG", "SMMT", "SN",
        "SNA", "SNDK", "SNDR", "SNOW", "SNPS", "SNX", "SO", "SOFI", "SOLS", "SOLV",
        "SON", "SPG", "SPGI", "SPOT", "SRE", "SRPT", "SSB", "SSD", "SSNC", "ST",
        "STAG", "STE", "STLD", "STT", "STWD", "STZ", "SUI", "SW", "SWK", "SWKS",
        "SYF", "SYK", "SYY", "T", "TAP", "TDC", "TDG", "TDY", "TEAM", "TECH",
        "TEM", "TER", "TFC", "TFSL", "TFX", "TGT", "THC", "THG", "THO", "TIGO",
        "TJX", "TKO", "TKR", "TLN", "TMO", "TMUS", "TNL", "TOL", "TOST", "TPG",
        "TPL", "TPR", "TREX", "TRGP", "TRMB", "TROW", "TRU", "TRV", "TSCO", "TSLA",
        "TSN", "TT", "TTC", "TTD", "TTEK", "TTWO", "TW", "TWLO", "TXN", "TXRH",
        "TXT", "TYL", "U", "UA", "UAA", "UAL", "UBER", "UDR", "UGI", "UHAL",
        "UHAL.B", "UHS", "UI", "ULTA", "UNH", "UNM", "UNP", "UPS", "URI", "USB",
        "USFD", "UTHR", "UWMC", "V", "VEEV", "VFC", "VGNT", "VICI", "VIK", "VIRT",
        "VKTX", "VLO", "VLTO", "VMC", "VMI", "VNO", "VNOM", "VNT", "VOYA", "VRSK",
        "VRSN", "VRT", "VRTX", "VSNT", "VST", "VTR", "VTRS", "VVV", "VZ", "W",
        "WAB", "WAL", "WAT", "WBD", "WBS", "WCC", "WDAY", "WDC", "WEC", "WELL",
        "WEN", "WEX", "WFC", "WFRD", "WH", "WHR", "WING", "WLK", "WM", "WMB",
        "WMS", "WMT", "WPC", "WRB", "WSC", "WSM", "WSO", "WST", "WTFC", "WTM",
        "WTRG", "WTW", "WU", "WWD", "WY", "WYNN", "XEL", "XOM", "XP", "XPO",
        "XRAY", "XYL", "XYZ", "YETI", "YUM", "Z", "ZBH", "ZBRA", "ZG", "ZION",
        "ZM", "ZS", "ZTS",
    ],
}
